version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
    labels: ["auto-merge"]

  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
      day: friday
    commit-message:
      prefix: chore
    labels: ["auto-merge"]
    groups:
      nix:
        patterns: ["*"]

  - package-ecosystem: opentofu
    directory: /infra
    schedule:
      interval: weekly
      day: friday
    commit-message:
      prefix: chore
    groups:
      opentofu:
        patterns: ["*"]
