queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label~=merge-queue|dependencies
    merge_conditions:
      - check-success=Evaluate flake.nix
      - check-success=nixosConfig rxtp
      - check-success=nixosConfig hcde
      - check-success=nixosConfig lssg
      - check-success=devShell default [x86_64-linux]
      - check-success=devShell default [aarch64-linux]
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
