keys:
  age:
    - &yufei age1m9azc8t9pr8580e035dlcrpu5cqvt4q3fvshmkd4ym54sfpxrdwq2qjtpn

    - &rxdell age143mhvlqr6lxvmkd8pehuxufy0a9xt43wpp38fk80t77jpquzm3aqg7k48u
    - &hcax age1vg42qr9mnrfgn3l34p974lacr8gqa79kxlvw2cnkzzxuaqdr69lqu0ueex
    - &lssg age1acupz46dkd20nqq8mktc8v7chrws6hnvcw2r5hpyd35ajg2gtdhqfx9uf6

creation_rules:
  - path_regex: nixos/hardware/.*
    key_groups:
      - age:
          - *yufei
          - *rxdell
          - *hcax
          - *lssg

  - path_regex: nixos/utils/.*
    key_groups:
      - age:
          - *yufei
          - *rxdell
          - *hcax
          - *lssg

  - path_regex: nixos/services/.*
    key_groups:
      - age:
          - *yufei
          - *rxdell
          - *hcax
          - *lssg

  - path_regex: infra/.*
    key_groups:
      - age:
          - *yufei
          - *rxdell
          - *hcax
          - *lssg
