keys:
  age:
    - &yufei age1m9azc8t9pr8580e035dlcrpu5cqvt4q3fvshmkd4ym54sfpxrdwq2qjtpn

    - &rxtp age16u2q8xj7fn2kxsuscm87wttvhzgm834s5q2am5weg4xtahfmnpwqvqlnj8
    # - &rxtp age1r8n6czl47683xc6c5xlpg6mze4rxushwwggg8y5rcx6u8mpr6acs6r078w
    - &hcax age1ae8xec0pp7sn0vtr2pjpe3mpqktqcg4xuuhc3p6yp6ep7tr7r32q3u6ckw
    - &lssg age1upmempprrdem66d9pz2clyvzczjd96mekjh4d4c62v69ja3d398q43ldll

stores:
  yaml:
    indent: 2

creation_rules:
  - path_regex: nixos/*
    key_groups:
      - age:
          - *yufei
          - *rxtp
          - *hcax
          - *lssg

  - path_regex: infra/.*
    key_groups:
      - age:
          - *yufei
          - *rxtp
          - *hcax
          - *lssg
