keys:
  age:
    - &rxdell age143mhvlqr6lxvmkd8pehuxufy0a9xt43wpp38fk80t77jpquzm3aqg7k48u

    - &rxls0 age146nukhcpcv3prnxrhtfampz6cktsz98hmkve4nra0ywt0ytyepnsjng489
    - &rxhc0 age1g4rgsh5allvuqgm4xd2mjwyl6s8ap3g0c2n2528jxjd3238xx3ls6h98de

creation_rules:
  - path_regex: nixos/hardware/.*
    key_groups:
      - age:
          - *rxdell
          - *rxls0
          - *rxhc0

  - path_regex: nixos/shell/.*
    key_groups:
      - age:
          - *rxdell
          - *rxls0
          - *rxhc0

  - path_regex: nixos/services/.*
    key_groups:
      - age:
          - *rxdell
          - *rxls0
          - *rxhc0

  - path_regex: infra/.*
    key_groups:
      - age:
          - *rxdell
          - *rxls0
          - *rxhc0
