keys:
  age:
    - &yufei age1m9azc8t9pr8580e035dlcrpu5cqvt4q3fvshmkd4ym54sfpxrdwq2qjtpn

    - &rxtp age1u0uu98n3q520ztc2m4f9wws332nu8ktszd403df7k434thumje9qezn99v
    - &hcax age1mv40mwz5tznsvj4su8xzrv4d3ew8prf7402se2ytn4f3ce5qxf0qpct22f
    - &lssg age1xh5ummespnq3t0ddt4wcfugk4ghdvmtrwce739uavv8rdmsshp2q4qm39x

stores:
  yaml:
    indent: 2

creation_rules:
  - path_regex: nixos/*
    key_groups:
      - age:
          - *yufei
          - *rxtp
          - *hcax
          - *lssg

  - path_regex: infra/.*
    key_groups:
      - age:
          - *yufei
          - *rxtp
          - *hcax
          - *lssg
