keys:
  age:
    - &yufei age1m9azc8t9pr8580e035dlcrpu5cqvt4q3fvshmkd4ym54sfpxrdwq2qjtpn

    - &rxtp age16u2q8xj7fn2kxsuscm87wttvhzgm834s5q2am5weg4xtahfmnpwqvqlnj8
    - &hcax age1vg42qr9mnrfgn3l34p974lacr8gqa79kxlvw2cnkzzxuaqdr69lqu0ueex
    - &lssg age1acupz46dkd20nqq8mktc8v7chrws6hnvcw2r5hpyd35ajg2gtdhqfx9uf6

stores:
  yaml:
    indent: 2

creation_rules:
  - path_regex: nixos/profiles/core/.*
    key_groups:
      - age:
          - *yufei
          - *rxtp
          - *hcax
          - *lssg

  - path_regex: nixos/profiles/utils/.*
    key_groups:
      - age:
          - *yufei
          - *rxtp
          - *hcax
          - *lssg

  - path_regex: nixos/modules/services/.*
    key_groups:
      - age:
          - *yufei
          - *rxtp
          - *hcax
          - *lssg

  - path_regex: infra/.*
    key_groups:
      - age:
          - *yufei
          - *rxtp
          - *hcax
          - *lssg
