keys:
  age:
    - &self ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMS5DHfxuhsH2yg1woBz1xTsRLDy+eZXgkGxYXJlYi91 yufei
    - &rxtp age1u0uu98n3q520ztc2m4f9wws332nu8ktszd403df7k434thumje9qezn99v
    - &rxrk age1tmdmg7wyptcavk3va6s0kemcxhyk2c3wn4s9g9gcc79e7v5g7c5q6s7txg
    - &hcde age1h6sszhgh4lqpjk2fegcezj4nlgx5q9cam2s4hzhx93qspmdv7ceqpls5sn
    - &lssg age1xh5ummespnq3t0ddt4wcfugk4ghdvmtrwce739uavv8rdmsshp2q4qm39x

stores:
  yaml:
    indent: 2

creation_rules:
  - path_regex: nixos/*
    key_groups:
      - age:
          - *self
          - *rxtp
          - *rxrk
          - *hcde
          - *lssg

  - path_regex: infra/.*
    key_groups:
      - age:
          - *self
          - *rxtp
          - *rxrk
          - *hcde
          - *lssg
