[ttf-ms-win10]
src.git = "https://github.com/streetsamurai00mi/ttf-ms-win10"
fetch.github = "streetsamurai00mi/ttf-ms-win10"

[ttf-wps-fonts]
src.git = "https://github.com/dv-anomaly/ttf-wps-fonts"
fetch.github = "dv-anomaly/ttf-wps-fonts"
