tofu: ENC[AES256_GCM,data:KDg4C5TxEtJqkVjTBt9yX3G1xVKOQaFX+nHk5F3wlH0kewK0FeerHS+Ndn1aNbdNpqUEyrPbMovYkfbOBlfulv414apEIF5AumU=,iv:kbNwAEW7nDreEp4MhZd1atV7AP8oK1F/KdAMuRP8aw0=,tag:FblHLcfQ3mgbzKM1CmOM6w==,type:str]
cloudflare:
  api_token: ENC[AES256_GCM,data:t7dA1mOoWyNeK6eIsa8XXfDWidKipOX5GG3msezaFQGlR1prm7vfPg==,iv:1Dr22sRQp8BT5tu06y46lHHuRFU6+GqAzDd6TIYgQSg=,tag:aRluxDmedLnCuWar/P5Xng==,type:str]
  account_id: ENC[AES256_GCM,data:1CD7kZppfZul3X2kXYwYc6XW34jQG54eK1zpJWc6NW0=,iv:F0L3NSw/1UDb9pXUY18JyeYqv7ohECWLumN9sB/XL8o=,tag:SbpF53zc4pnS3GJM/nqzmQ==,type:str]
  r2_access_key: ENC[AES256_GCM,data:fr7uVRnsaQcHshV19m2MtCjOuWC17+JK2TQFD/RBJVk=,iv:67RV3S0VY6ygOww8pXE/uDgHH+fmLJXz6dg8KOo7GxY=,tag:VGMeP3uwHvS5u5IhpxC/0w==,type:str]
  r2_secret_key: ENC[AES256_GCM,data:EawblxTieaunOLXFInZw5Cy+OaVDcRazcEsbb6zfyu/GvhBydiT7Jtf2O+OWtnA98n2nfidkKQu1ke5+u9lOkw==,iv:HotwSnU7gjRZ8FiWmeMVUr6+ArOOYXPGHMNsd/f0ckY=,tag:7ihKDdwdfQ5Jq7kNK6XBHQ==,type:str]
hcloud:
  hcloud_token: ENC[AES256_GCM,data:IBrnP/LyCcjG3KJgUUAmiFd2kuNBJYPBG4+KQGfPyGueHbfMhxGfBYjtigphTFTovC8ZH4DHNhOPqoba60U8ZA==,iv:2+plAKQleOcJUbfElKhTrhLAqA9yfXGeHVfeCRSICJo=,tag:0SzJP6lFym630FCmNlh7ww==,type:str]
aws:
  access_key: ENC[AES256_GCM,data:76zFXRKTSPyfQfrvEdXD4MUu278=,iv:oH3DuG8DIE4uk/ETmFWoAXYoq2qtpNjlVFTAv1tXmig=,tag:a/FwaIFTEVmXd2hukEHlsg==,type:str]
  secret_key: ENC[AES256_GCM,data:mvxvpeHGSWkr06pB1Kk93HzkFRZoBQrdchlm4jsBKxSmnEeElN8+/Q==,iv:bnJZMlCalYuBl5OpX8jIOgUk/n3jDVonfTtTUBBsawM=,tag:CMIqEYATr2eERXnAhqP3Gg==,type:str]
disk_key: ENC[AES256_GCM,data:IMq+zpV0YLHIHsjlOOeX8A==,iv:G8ECKYxD+TWvM87Wn9wa4TryGi5I5iX530qdHEjG5QM=,tag:uLsyNvLxXi4nyMFoX9zHxA==,type:str]
ssh_keys:
  hcax:
    ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:nAu0zWWkdlF7GR3Zr82lTIT+ECwDe56Cou8ctnFoBt7QEKM9ISk8qrfn8uLHssQ04NmekQJw/AqcBOi2ByXCuIOL/C5j2sgfAM6Q1D5D0YZRbLWxXj1CbsnD,iv:lus52uiHVNHxIc+xO+fsUykRcqyd5DIj7BZVIpWvo7s=,tag:FxUKecMCsmvzJ/q3ENoA8g==,type:str]
    ssh_host_ed25519_key: ENC[AES256_GCM,data:oSnXzAsW9DHI+QWKJZ8fUBUeo79CYRS5pTlzkm5MXJ26X1H2Pz2u7jv5W3B90khNoAlRU5dUGUwla3lzsyEx1tABw9ZMUF5HbXN0bFNibGAVxHfs5D+X/n7gRZscNGGkY2HBGvKJoM16roXPPPS0dMa6l2ODj6MIcOCRtpqhdZkYoYw3zSN25OU1RM6QPeVeGLVJOJNr9d+stKjjwtw6ULigthCOoMN240Mx/BiSvZQeua4hCOtsFdxF/1awB8e1IJAZfaozRZIWTyxXjL0QXUQcr6L1MwyANEmdwUXKotPDEqhd/C3K5VXQQihCNvhmGk29EY9E7qkQlOQOKovR47svy4zxfHw8Q0tNZm9wReBmMcrdYiKQETAsTaYPcbkF3fLuijOrrukDQFQPaFRhHEh2RwzzzZpyLtrG56jNt635KqFp2oqIfFpaGr7sPBcccklMKBEXpsXWnuGGMrVQAEO5OqJj5lB8YTzCl6dCmbUo5DgICTc+qNRswTC8b1dfbxCYwz1UXWrU+us2OGTa,iv:zeiwwq59h+IerQdbBtby7/a7KR2qMVyGAoElXqpXUo0=,tag:4HZVhuzP5Zerh29jNedZQg==,type:str]
  hcax_initrd:
    ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:TjCDjnxXRMmFI/2YVkfKpVW3JncdZwvIhPK41cKGoRBeAqc7O8nryQBIsJg/F0K6resDOUfOUG/1AjM05F1xajYa6wSPRGpCqDRgqjhk3DUGKKPZHJsPJnNg,iv:JajPyACPjYC67+mDGMjNwzOlo+IVU6W94k7OJ++h5Z8=,tag:Xi5jBa2SCJCzIZ8uupGdQQ==,type:str]
    ssh_host_ed25519_key: ENC[AES256_GCM,data:jxz9mf98x2XFmfqV4gioIz3wBXnMzatV0ihi/Y18M2wOytD+GSruiLR+7pZct+VKoXCkSeCwE6/BP2r86lPicvfD+EIPnMZgZ5amsqlAk3h6dZSYF4S7Y79MsxsFcpSY1yPb6HwtCHY+jsMAfRNUyoVZEmY2mpwUaIfJsgFgKgdZ6yZfDZzmdN8x9m+5PFmRiqiBk8iQU5G9EMKuuJOQkhp6wLPuSlSCZwavELmk5D9ltlufCzKw4Ie5LwasOnfGj80o1puFyD9RDwhn4CcsxTwALqHLRWZvaNacSoAXuMxaFjuxLRYQXX1XQcnj1PqtzJBJAPBoag+qDEnYWo7w2T3W/rJhCfr3Aw0c/C6FsfWhRPP98tw17uHFQ0J6meFpCTi7BmZw41zcPIOwkuJHL/NPnqWr3EDZ0lR91wSEUuk8NkYmNpIU7BjOIZLUhOUUHvhCIkIet9M0Wz8qW2wqRsAKqsWyMlCnYj3zA3AeXS4TsYRgZ1waP4t6pmmNDOoo97DueNX9gAS8J6xi+/DO,iv:cfusqCCHDNu29jvJC+Zn7XsRMoEpz6II2wP4cHUo6Ak=,tag:Ke8jhdBE/8cnVsarPu1Jug==,type:str]
sops:
  shamir_threshold: 1
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m9azc8t9pr8580e035dlcrpu5cqvt4q3fvshmkd4ym54sfpxrdwq2qjtpn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZzVRdTB0UCtCUXZlOGRh
        WUFHZjJ0UGRkTXdiM29BbVZiZWFEQ3BVK0RFCmYxTk41RGlaRmVRV3c2S01iR0hZ
        cHg5cmNOa0piMS9YSEJreHlYUlJ1ckEKLS0tIEZoNFNaRjVOWktkbk1FQ3NMMFdO
        TnIrNUpkT2l1ZnR1Z0FXWEc3ZjNhR28KIllLjx4Jg2NApXfUuOIXy6Xg2Hi6/jNZ
        0okTPS7m7puUWaqyjmiLpXo9n4yT+f3CVWA+F4/0ShbreUuFNB/ulw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age16u2q8xj7fn2kxsuscm87wttvhzgm834s5q2am5weg4xtahfmnpwqvqlnj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUENNMnI3QlpOR2FUYkN3
        VWhLbGpHUm5aUHlraVdPSmFyQWdMbHYzd1NVCjhGODd0YURJeW5jZDJsY0xoSDhr
        VEhzTGtSc2poSTdxQk85dkhyT0V1bzAKLS0tIFdVVjhVaHVXbUxOZFFuZVJtWDB0
        c0cya2Q3bHdDaXdjTVM4N09naXhLdzgKnLCUCuOpYchl8jBl92jc+QgNbkU+Vrd+
        R18c4OX+uyc/maFU31Nk0tBEFzcbVG1oaG6jxgd/xqm8GUk7sZA3qA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vg42qr9mnrfgn3l34p974lacr8gqa79kxlvw2cnkzzxuaqdr69lqu0ueex
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aE1mdHZPR1p4eHVuNmph
        SkdkZDlma1pMR0UzQkxLOGFGV3VxMHlCUWlVCjBGZHdaazE2cU53VEpaMU9EZ2tj
        MnpoNnNrekxlVmFKSmZJY0I3Z1FUaE0KLS0tIE9nUG5TSk9CN1RLZFF0bElTVm43
        NEEwV1VHbzhNNjAxdm1udnJmWS9jelkKSuCoT6jCkDR9y636davDU5SIIY+lVRgg
        Cw4F78SmsToLAJ5mO+B2e3yhWtygSsMGQWJMNwIyrqEO/ipdES8g3Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1acupz46dkd20nqq8mktc8v7chrws6hnvcw2r5hpyd35ajg2gtdhqfx9uf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTam5RMDBqQVVtTzFDRkNx
        VnJLdVdzSWF6a1RxV0FXZFovQnF0ZDg2VGxBCnhDS0RFQzhYU2t6NFIxbmUzMXAv
        dy84Zk9hZ1luVW0rY2kxUDBHQ3d1S28KLS0tIGVTMUkxMSt5OTYzTG5saUhheTht
        WXdJRTJjc01pdER4ai9yeG9OVEtOS3cKAnceUWFVHkDZB7zytdr6FyEBfzIWTNKd
        4QfDFT9b/2cbHdHSdfneq1UmyL+8CeQ6kWAy+mH4KrJXXPERV7BJyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-06T07:48:01Z"
  mac: ENC[AES256_GCM,data:lzQhh9p5A+fBeZbVCIdVtVkkLx3EHt5NXH77jagTtwQSb2IWU294yllH1D4nXV1prMwHxIjQl3lWd1nYYvTO5lUGf2ZjXOYsWEaZGzsvKXwOZmdmml8XEV3245J61BZxMIXLxftv1XS0tZUbXGg2J6QbT19ZBLBQ9elKYCfkNpk=,iv:910dDFmCaXBNt8Wb5zluSsIYQZ2KNyJJzZRLkQocx+Q=,tag:gnb6SeehgU9TmqWsec/FtA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
