tofu: ENC[AES256_GCM,data:KDg4C5TxEtJqkVjTBt9yX3G1xVKOQaFX+nHk5F3wlH0kewK0FeerHS+Ndn1aNbdNpqUEyrPbMovYkfbOBlfulv414apEIF5AumU=,iv:kbNwAEW7nDreEp4MhZd1atV7AP8oK1F/KdAMuRP8aw0=,tag:FblHLcfQ3mgbzKM1CmOM6w==,type:str]
aws:
  access_key: ENC[AES256_GCM,data:76zFXRKTSPyfQfrvEdXD4MUu278=,iv:oH3DuG8DIE4uk/ETmFWoAXYoq2qtpNjlVFTAv1tXmig=,tag:a/FwaIFTEVmXd2hukEHlsg==,type:str]
  secret_key: ENC[AES256_GCM,data:mvxvpeHGSWkr06pB1Kk93HzkFRZoBQrdchlm4jsBKxSmnEeElN8+/Q==,iv:bnJZMlCalYuBl5OpX8jIOgUk/n3jDVonfTtTUBBsawM=,tag:CMIqEYATr2eERXnAhqP3Gg==,type:str]
cloudflare:
  api_token: ENC[AES256_GCM,data:t7dA1mOoWyNeK6eIsa8XXfDWidKipOX5GG3msezaFQGlR1prm7vfPg==,iv:1Dr22sRQp8BT5tu06y46lHHuRFU6+GqAzDd6TIYgQSg=,tag:aRluxDmedLnCuWar/P5Xng==,type:str]
  account_id: ENC[AES256_GCM,data:1CD7kZppfZul3X2kXYwYc6XW34jQG54eK1zpJWc6NW0=,iv:F0L3NSw/1UDb9pXUY18JyeYqv7ohECWLumN9sB/XL8o=,tag:SbpF53zc4pnS3GJM/nqzmQ==,type:str]
  r2_access_key: ENC[AES256_GCM,data:fr7uVRnsaQcHshV19m2MtCjOuWC17+JK2TQFD/RBJVk=,iv:67RV3S0VY6ygOww8pXE/uDgHH+fmLJXz6dg8KOo7GxY=,tag:VGMeP3uwHvS5u5IhpxC/0w==,type:str]
  r2_secret_key: ENC[AES256_GCM,data:EawblxTieaunOLXFInZw5Cy+OaVDcRazcEsbb6zfyu/GvhBydiT7Jtf2O+OWtnA98n2nfidkKQu1ke5+u9lOkw==,iv:HotwSnU7gjRZ8FiWmeMVUr6+ArOOYXPGHMNsd/f0ckY=,tag:7ihKDdwdfQ5Jq7kNK6XBHQ==,type:str]
github_token: ENC[AES256_GCM,data:PSOiNyBvDLk7fLxrCfAg836Y8juthKB4Luva/fnwlWTBBWiTeeWj3ZRWnJHHxr+1GoSQi+ozJB+bmhI/A5PoiUTIu9YKJiA98vYOamO85N5iVqxAe1MzeVl3xQOY,iv:JCQn0VxS8dpGw9Jip+xWfU4QMcYDQbrM9wgph9Q+YkQ=,tag:7oXOZgFO+FBlcBryA4DBFg==,type:str]
hcloud_token: ENC[AES256_GCM,data:hs2AVHUUxAHkzxp2S+7xeXS/0d61UkoW/TpDmMqAGDhgg9ONhMW3zUeqSwuW177bekEL0atcNCJg9i6eyc/LSg==,iv:Pd44beGxaL/07nbLxowstwSZHANqthTbtWtp47GqDDw=,tag:PJZAG2OiROIg/kurYirxgQ==,type:str]
ntfy_token: ENC[AES256_GCM,data:eftM14Edmhi2V7cevVA1WoMZbqv/duKoFcwyd5tK6bI=,iv:BMxYP2eauIn3ep1TwRWJM9IlLfWtXGCUKuJmBWHP9H0=,tag:pgcg7xxle/T5IcRR8jxzuw==,type:str]
disk_key: ENC[AES256_GCM,data:5DfT9EjEXk1X6DvKqdyRQQ==,iv:0bab99JOk9wcRORGZDVed/NHuR0EbEPGR33ijm4FFOo=,tag:dbL6KBTx/fVVuYZhLI5l4A==,type:str]
git_public_keys:
  id_ed25519_sk_rk_ybk5_pub: ENC[AES256_GCM,data:3wPBhVW/M2Js0KVWiEKiXKwFM9w1R6+B0W2ifXafX/P+tPL3x7/hLup9H/1QHfKOVmgTfS17IPcEsSp+qyUF0fmY+GCT5low75so9OnLB9dXB07Sq300g+9vNcDCPH552EgYXA7IY6EYJdkU/Iuu6oLg2Ht6iiONc00O5WdI/LSjqkwuDZWXc7xCfg==,iv:ouxLZ/v2+jzL4wh52lsBo5TRF7U0aT8ay5qgSsUupGc=,tag:0Uoym0sJzsYcv1+Td2vvag==,type:str]
  id_ed25519_sk_rk_ybk5c_pub: ENC[AES256_GCM,data:Oc6Ae2b1v8dNDeT3YioV035bBggixZONyEPYoU3dhWMiQP+kN7EvZ7B33Gq4PCwHr09sLctLqKkfv3DQHuhzClRCH+XgDXvaKaQF+4oiHYnsZrIEoLUEWsXhwSEtI1NNad/YINPQmKOQlxsHUd6+iq5nveouzmdQbg2vPDRLPfqewGYGWq+yY8wNTg==,iv:9glafLPNzqwnUW+DRi75OPx/BEVBECYOdYrHBmuPIks=,tag:kP5+kNbaRPM7ADzdhrM+6w==,type:str]
age_private_keys:
  hcax: ENC[AES256_GCM,data:kdCydkime7VSSnlMpIsTiw9p5+UrAkpjG478H3G0juB2Q4CAJ5ywZCgMy8hDNtGjcJclTi5DTR/TmC11av08Ery+0TpPC/B8x+A=,iv:Js/0meD98ji9dqrmIWl41yFlCW1SzpxoNLuqpc/gpZE=,tag:UuQ83qfwZg4CyrejT8FTrw==,type:str]
  lssg: ENC[AES256_GCM,data:tNPqi4CJmzusZITDXPtE78lRJHpLBrxY+7fR5U4TIHNDSqCZuOI/bVeqwRPyEYWQmpZM3GVIv8TDqbRBzZ/e2Gqj8qJ9eehCh7c=,iv:BxY2uc9EwaFqc+3i5X6TqIWwFzjPzpVZdivbWigOXcI=,tag:S/EZNZ94LUy+HTHAcnRpPw==,type:str]
  rxtp: ENC[AES256_GCM,data:OQRihuIr7Oc6tEvoMOD2BFRiOntpFGM3PQZvz5tVMLEZ6m33q7T2KNOvjJ6fsWbilyW17MBUkkVkCY4r4eyFPdp9/OFy7/8h0o0=,iv:hjFZNgAbQy/MuV28QB/1ohFrboRCuUnRV4A1CYzTCew=,tag:6gg3yzdeCZHARfTISb3N7A==,type:str]
sops:
  shamir_threshold: 1
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m9azc8t9pr8580e035dlcrpu5cqvt4q3fvshmkd4ym54sfpxrdwq2qjtpn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MURPamdDMmdVbElPUXdS
        L1NWYkdnOXpCWVh0enRnL3NXQzh2Mk9oNml3CllBV1ZlTm5HOS9qSnBMVjB1NUh5
        eTV6WXR2aVEyelFrQ25BL3c1YmwxbTAKLS0tIDNPLzdtZ0plOFJpRmI1Uk9ta1c3
        cE1sdUVsWDI2bytFTjV3bTA0MVgyOFEKjHC/Jb2y0e+CDr01wtWnNU3DF4kT6c14
        Rvn5CVGaYjRzZBzGBtoGkTCIZje+KIH7e3MNPdNsZgWVOpFuzMayjw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1u0uu98n3q520ztc2m4f9wws332nu8ktszd403df7k434thumje9qezn99v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaXFPSVBzQUg5bEI3cFJF
        TWVXc3FsazgzeG5nOHJPMVF4MzJocjdBQzJJCmt5d1lxQmR5dzBxUFMzc3JBOUI3
        QXlCajBRWVdNRjAxOEtLb2c3aEpmcncKLS0tIHdJZjZ3cEtLZVZ6VlJqQ0xyTVhI
        eGNPekxmUE9lVnQ4U0ZMaWU1ZmN0Mk0KRMEtQn9OsU9fCmTn7yBOobDfbtJLqbje
        hU5NqXn2rnMS7kQyrlJG7EYOLxRPp2oUbaWwQ/w+xg1yOZw82aS1Kg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1mv40mwz5tznsvj4su8xzrv4d3ew8prf7402se2ytn4f3ce5qxf0qpct22f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Rng1VkVzK0RDNFZJMDg3
        ellWVW9hU3FSZFQ0T3hHTzU2UVBQNnVTbFRZCjIrY2kvTzNnMXVkZ2JwTWJpZGdi
        dHkvejg3L0lreEJKM09PVDBISVBYaUEKLS0tIEp2UjRWeHNVTDdwa2JMQU1WQnp4
        UTkxR3o5cFlDK2hIQW5hQ0p5YmgvaDgKEXFLlcwgwOo+lROTHeD4V2egzFRA3IZT
        aJmzOJpXV3S+V+Lhag9jyMU0ZNh97YiZ5UU25UIcL382lrJXXfMpBw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xh5ummespnq3t0ddt4wcfugk4ghdvmtrwce739uavv8rdmsshp2q4qm39x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOEpYeU1aZFhPU1lWbnB1
        dWN3TllnNGhEdng1N0xBeHhmME9qRzgzdWlrCnVqVTZpT0w3citDeC8zcXp1Ny9v
        cVdCWFlsMHNQdUxyOGRSNS9oVnN1RWsKLS0tIExITzJUb0ovODFNRDN1b1ltMmhl
        MW1GanFJNW1SL1huZ2FvWFEwaXpFYncKujyi81ShBoHUbL3pbYpxen/LZuvxo8wy
        yiDwE113NGnrh3jN24NOl1xUFKCyeMFcHx5ztg4wRkdASTCgGKVa9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-29T16:59:46Z"
  mac: ENC[AES256_GCM,data:26W/xttR5r2MdOUyP/6XuWO9YU+lq872fzNXtGGANrB+iL8qQh9ZvvPzowW+vcaPz/Qp0gQ59JKTgU6aTTh2gHWS7ufnSkQkQIhe1f2274CUZS6nTznE1wGL9+WGtdiM6q+1KT+7W7SH4HddW8XVJxFvCNVZDfuOpHP0A3x8mPg=,iv:vrup0pkJIVrMNK8xHuiaPlIUT2f/wJQz0uMWsieEm3c=,tag:PMSJudvxGEUkD3Sb92hzsA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
