tofu: ENC[AES256_GCM,data:IIYEUHK7PJzRTNlPuftWQs06pp8s5UrtGtls5CtsG8/9Q5Rhg+ROXIgxfgaSLUldNmO6ckBL41q3PTGRCgPy9uBOcmzncoNuQqo=,iv:kbNwAEW7nDreEp4MhZd1atV7AP8oK1F/KdAMuRP8aw0=,tag:4GxLMZeOdBYJ3wQRFpD6rg==,type:str]
aws:
  access_key: ENC[AES256_GCM,data:HzcU3zCrw9pC8btnoC5pD8ACV7s=,iv:oH3DuG8DIE4uk/ETmFWoAXYoq2qtpNjlVFTAv1tXmig=,tag:INk0QUEEy8IiQROr0r2aGg==,type:str]
  secret_key: ENC[AES256_GCM,data:cb8Yg8ue8LPiOxjTeN90L5B7m7mefOnqGRr25jKCIBo1ObA+ULakIg==,iv:bnJZMlCalYuBl5OpX8jIOgUk/n3jDVonfTtTUBBsawM=,tag:yFGl6wK+tYhyDagcnYXSAw==,type:str]
cloudflare:
  account_id: ENC[AES256_GCM,data:6tZwhXjl/JdU0S2sH3On4I0ejy6GrI/A8fL+ZDEUE84=,iv:F0L3NSw/1UDb9pXUY18JyeYqv7ohECWLumN9sB/XL8o=,tag:ou/rbSo0WRV1lNB9bAH6yA==,type:str]
  token: ENC[AES256_GCM,data:DOWy9TXSh8eMJbuXMmLanvRcYUebjSUx8JWMnJYT5A7vTPtmk8A13Q==,iv:P41Z1a6YKTwTU6Ke+qXYEpqOuBLQU8zyYmjbxc4r2Cg=,tag:TC8f/7ro7b5ElxOauxGtaQ==,type:str]
hcloud:
  token: ENC[AES256_GCM,data:0h5wyXiF9rT/wHR9hR046Vd5Hkf5gQOIl29WQ18N6VuiKBZqRajmbdnBPg1pQqWG6yuumK8D6PT7F9Y3NMY+iQ==,iv:WX/nP4mupp/G3eyIOj7zdS6BkIbsUhvAV6dnGxMQDqk=,tag:m+vElxVpLOGXtf7lIimxfg==,type:str]
github:
  token: ENC[AES256_GCM,data:wTRyLhvD+7AdFqbFjpj59lEbjhZqGxyjMZhek9T7fdDSYFftj4k3ZoHEqdsG5g8WRFCodV6PHYavsKrhJqEjBrqNbOZliOXeRWdQFKoe7JULMOokXlrbuA7McvTh,iv:9DWfkOWHMm1yK662n/sVxKvpo/FhhywYuULMOqVdhXA=,tag:D125GVh7prE3aWHCSeF3Tw==,type:str]
  app_id: ENC[AES256_GCM,data:0uPGLn9tWg==,iv:4XJz3rbtRLJpeHVz2o9XyQPvbIpQZlrtaa6JgzHdra0=,tag:e0Dmj/LP2FmjQ4vPBr15EQ==,type:int]
  app_private_key: ENC[AES256_GCM,data:+VYPp7K4ytcfRbhHK0+sdOoMQ26DA2C72fA46Ogo2/ranQsNMas72IcGkJFLNMFp25qCy/OVOkQqKLAwKrwnVaVClxRkCyajvIS1gtTgj2w+3a3KCQmjJwMdFzFBL4cINUrlx4AkbmCVR41I5ms+MQGNU+oBHQFi/wvfwxj/pTa93zaa2bvFcz+y7t9qRKQVx2sHIvjVFpTgCACZ3BBFPHJaVqHvl0RZkect6GHEBkLzMckv9x9JV5hJseKKR1okQsIUo7/i8C0KPZrbjB+IH8invQVJAWis89Nj4EeyZ2Cb0Fszi1GNQCXi6hiwhPgwCqYmbHiKUsqf/cvORHkNvBi7gxwwqsPRXALF+bZcFvFts2hUvbLdahJOae1wKU7HQ/MOMOGlDo+Lq/aDGE8ibYgxT78NkKbgA/kAyeb7EKyDnWkYTiV7JH77fDdTnE2R7/UNoBtyDxbyssp8/MbduBsZdc7eC+iJfvV41goZX9si6dnxGZz4PCcUah5/HJQL7cKnTDgAsF7C+0cY2PfPhEhTvnMuoOCeM0q7oSKagyni/9A9ciHROYq7ODUYP2+Yk0TUyPOc+0LT1JFHXT/ScvjQqmvRORsZ2gfGDF2b/Kh10HRtOAtticwNlpyLW1SlL2OrB9RDYVhxQwVVLecZ56FBKt7AbEL9wdF70/qn1b+k3bmLwiR1yCsSYaMtQ1ELXLP4XVPEqoHzwEecDouRJghQPFLZ2YUfK4BlB14o27w4Yg3u4NWRjMu5GRB9kKex6mAqQyVBFvRV6/wbuKZlx7ygmTMK9pU0EQ3ePW8tlJTir6M660jNFK7qXFpZl0a2IdGs9K7MCS8+EfGE9/kCDf0uenlrLVg+nS454TYujS7Cg71njY7CCAiV2yrgDnOF95TgpQUHhr0nlJWWRTvxjRxqUmxCvSy20bP7nnaywlCOacruieP0PuY/URxAPqqg6W8XqLtu52d5NjER9Y2n47KZgvUcvuvUkz6d6uHMzryrkFsy8fqQ3lhRcc9+FGapHjwcJ3XVYJWOM+Ql+ZhFIIQ+kSj3iOMVTsXtgRXuxv4xpt4+sMLS/+lkQ/ez3duwDGEOzsEN7FdfMnlxAgG91r3VX1f3/eKZAUrhxttLCRkqV/XnMlg0FKIY2RcBoD/wYakvUFPBzVrI0zxd5RXQmnKvcLxiNDfFdT4b8DAWj+BXvfi4rC0inYqCOMeoMQf71l9sEfUfYAq0QWI0zKMHsBMtQA6Y1aNNomheB7tZcqNKVrdaJHGb/7zIdJdjGanP3MG5oInLGVhzVHD0dqqQwJsZTai206Ah5qShpGfuuMB0zmw5oKzRhBZQUBvNQNjP2k1CtzYFuQjao/FOhLr9WuBusHUh0EIAfM5H83BQjronzqFXHv4B6JjWVzn211yzk+jzYGyWXuYBJMtdFWzrlYjl5SEc5A3pmT6un/MBcj5EWDE953FSiRtUEZXcWyQb2KpBviz+PVuqiHvbPV7j3cO16vV8+qFozLnS23nrh6NI24vzb9/ufzJyAvEoYDdbxSsgahMqyYM4luoruGNoVns4pqStj77yxtEJBUCmySX4ihl/LMeG12Kp2DMuxsOZfxLv7+Au2SIbrZPPeSuKv8oMzx7OkF1xQsOib1MeRxV3XG9p/QklZPm6qGXSkrEq4Km3E92XSMGHlS4DsOmXJWQcnl7k7T3n1vjKaNqycgR14VWiNSwHmzSG4YgdXeKd3vgNHiV3sBUl5zPrLf5Tix8haTKPAW1s066KM5OQuCTuK2QND+VDj6DLw/5Q6VbF8C4JXkjrUPpsrAYQXmsXjrXWOtNFWt1aMmSz5y3yZpnVwL/H5pyUM6DlfAQjWczb8b5lubZaDogBeaBZjcvQA7AZc1m1ozLvmgFbNMnUN1/+OJXMI4C6UStQlr5E9Eg87qfxL7RrWQscOZGVG/LY0H8ayDCZ19mdFihwDLhCFAKBeonu9Nc2GzEBcvRgJ0pfXSpF+HFiHAvY/kEXc3IOwQCdh/KuJn7B8r08P8h+PeGZuJPY2geZD+8xwrJ1qgJI0yQ8I9BKBlDmS519Vfd5FZrJKyuxKf6VnoXqFO8ssmw6L+UuDh5ezKe/i+UAVaUJMTL0y9alAtJ6qzNsaTBtS29lscv1hE8I3kpGwvE6QzrAybesa5TaKk6/xX+/WWm3V8gR8F6yOed5SJ0SKZ7p/Tb3c+sIj4qYZ+um7LA/qbYJHw0VGBIxXtW5bfcSCWY=,iv:mwI8M1BQPfp2UsqGEWnrCAMmDD55IRC9M6qDFat4sco=,tag:cmKWdehpJAHcUu1Wdmcbbg==,type:str]
tailscale:
  token: ENC[AES256_GCM,data:7D8egY6pYX1mZTOt+Z3KJOcq8Dv9RLhkzR3kIMnyu4QhoSDgZtiEGAOvUmHj6r81ygTRE66XDZVUowgOBA==,iv:aoiTEIpRAlVEYxTH96lSUC6S8iPxE4IZXiH6t9onjNY=,tag:XoAR3XCB5Oj5J6uSXw4Y/g==,type:str]
sops:
  shamir_threshold: 1
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMS5DHfxuhsH2yg1woBz1xTsRLDy+eZXgkGxYXJlYi91 yufei
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGRUekNWUSBoTXgv
        bGsyRVlyYVRwUmk3QTFwRHViL0hyYnJFaGFIcTVBczRKRFdtcEJRCnpob2FteC9S
        d3d5WWswcHJaakdLOHRMam91b2J4Mlo5TUlDOExaODlTS0kKLS0tIGIxTUhnVytO
        bVY1WktUR0xXSnNOWjRNcGlGanNEUzBZbEovcVl2RUUycjQKqcF4u/TRFpXneBIV
        9OYsF6I9Fh6P6rKqFX8LaJSDxBKQQ2XG7uSwGGe7y/CMfv++EbNVwQtWZoeip8KH
        aChZsQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1u0uu98n3q520ztc2m4f9wws332nu8ktszd403df7k434thumje9qezn99v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOHVYWG9mbmllWUdiMkN1
        czY3TDIwcTIzSVg5a1pqZmh1SUZxVmQxRFVVCnM2NCt5dDVmcjBydzRGdjBha092
        d0RkRXVTZ3JVWkhzdHFSWXRIVUpBN2sKLS0tIGVYRkdjVzN2R29pWFN2eEQrRVdB
        RkMvTVIrSlIvanFwQjBUN1B1MFR3RUEKiaWdQ43lq0tzXpqB7nlVXxb/wUrSuU7W
        k+jRiMoZtXJD76ohnwKHRX2Jf1td3/qhfNGwZN83rfRu029UaFm5dg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1h6sszhgh4lqpjk2fegcezj4nlgx5q9cam2s4hzhx93qspmdv7ceqpls5sn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bkdaL0dpMFFacUJaZWFk
        aTFjSWRENSt5c2ZsMHNUTGUzVVViN2cxajBRCkJvN243bmpHL3hSaWJOK1Y2cks0
        RFQ1ampITVB2MjMvaDVuZldsTGkxZEkKLS0tIFVQMk9Tc1E4TGx2U3lKWStMRmpH
        cGFlay8rVnR3aDlJSXpyNnRVc3VZZzQKFUJKp2PJdf2CM4KddHb2fvxKUiza/3lK
        cCZwpdrPYo05cMwsg3DOqAutDRbeL+YWXHHFhjtJEsFtgQW4bHk2CQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xh5ummespnq3t0ddt4wcfugk4ghdvmtrwce739uavv8rdmsshp2q4qm39x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRkxuWGlMSmtEVWhWQ0xY
        VnpaZmtBbDVVcy9KOC9nWWZkNithS2JSeDBnClZqODc0a091RFpmY3pCMEhvTHZB
        aXJKaE9qMjdvRHpmMXlGOFpuY2hucVkKLS0tIGpGQ2NRblEydkE0QzJUUmVBak5I
        NFBtUVcxRDRrell5ZTJKQVdpU0lQdlkKwfJiR1/5EcFvhZN2dX7hfZN/eGxJsxp5
        smvSTvNIOWIiQmb2XtCI7EC1NF8Yv2USl8bnevGTMipS5xiCVcR06A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T13:40:39Z"
  mac: ENC[AES256_GCM,data:gpDD49Ar/uC17icW1n2fLjvaYkfve9aBOD9Cx/jGHoVs8tSUN20VySp4aS8NcFy66Udng59TQI/XOm4RMzYso3R/dURByKnkUdji8rVXTwYQHKGd97j+z2hTbRD1y+G8epX9mJ5g9u7wu25eoFoXPpQ/BiKovJW1T08ojxuHfSg=,iv:mrDbtpRENBMywtjwphyI6EqlJWZuPOhg5c3+rCGYEdQ=,tag:2oku8Hmm8nFDBuIK66z1WQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
