cloudflare:
    api_token: ENC[AES256_GCM,data:7sxsLceNondUCFK9lVbAE9G4SiYpUg6vMTQS90CMbd0fFjynrZCygQ==,iv:NnZn3UoR8t3dyWLmjkkdUg7Zm7/hqgavRRtoSIkS0xU=,tag:wMfGSNvzKxLeRJWUfpYvyg==,type:str]
    account_id: ENC[AES256_GCM,data:1CD7kZppfZul3X2kXYwYc6XW34jQG54eK1zpJWc6NW0=,iv:F0L3NSw/1UDb9pXUY18JyeYqv7ohECWLumN9sB/XL8o=,tag:SbpF53zc4pnS3GJM/nqzmQ==,type:str]
protonmail:
    verify: ENC[AES256_GCM,data:35pUK1Wj7MBTMh/3yEANUgVtq8+4odiJXKsiqd+I0gL32QstC28ooeRuteAWL11sgQkuT3AShYnCCJ0VrgCr4A==,iv:F9dg4dT+d6yz+wJ18+5k4oM9WXE2oDd7fLOhRHerNGU=,tag:CMw8AFOtf83+r4kQTZaZPg==,type:str]
    DKIM1: ENC[AES256_GCM,data:zuLhP/yM9j0YqZ9xehOreBqF+2nBtG3hi6p4Z2Vk53OMgNzPVOETC++niTv/EBNRFVabcOJ/vlkOguWzFNuGQ/BcXaP96F8s6aAQwb39rb9ByD+KWMpeXX3qTYza,iv:6kk6FdJLrn3bqJQPH5iWzTa3Nk3q2DdbjmBPVo5hC5g=,tag:YshKPq5K5NedbOJvfPKGsw==,type:str]
    DKIM2: ENC[AES256_GCM,data:Rmy8Iz5sMl3kksuCFX0Kk9qG0yd33CLPZ2P/xh6YlXHDwmOiDmYinQTYSTE2PObkpzMHR/AzGFAMAO3v7pWXew5EqgtDjghbYVDY3sigfimYqwMLY/T2R45U58Rlww==,iv:eXKPS5B1/yxIuIsBp+aZ4Glpcrhas0eMj7dpi+DDUf0=,tag:LtjkIUv/42NaGoGCb2nexQ==,type:str]
    DKIM3: ENC[AES256_GCM,data:qsdYx/NXN0ZWsptnuIHrBu6iU2dTszQFNAEtCklDZz2gCpkRl4HHLPa/63t1cZefvPtVFbnuvXTiTamNN5zbe3Tb0zd91tsFfJwSTaqI/m51pAbE0UzJLSeI5iwQLQ==,iv:Qfi/t4EHWa5AkI5O6FI80mfQFcJGe1Hnmnc7tCbjfho=,tag:rnBFwXYu+8w+G2pzi78fOg==,type:str]
    DMARC: ENC[AES256_GCM,data:LKA5GRsb3NGzbScEJI41ABUF9iYVwp9pErnePdZ340bY1ofHGWxSdF3i11pK5OtzCQ5ChRsqCtni9//Xk9oqjcVRvsoOQftBCAQua/LMgX1nd96Wrr/p25L6O7zNBZot8RWR99hXvLo=,iv:+FWMjt7mgegWjDtfMgmFBURGe69gez61/6Jy7p4OrlU=,tag:eHOHaXd6IIm/tSNwJBwUyQ==,type:str]
hcloud:
    hcloud_token: ENC[AES256_GCM,data:IBrnP/LyCcjG3KJgUUAmiFd2kuNBJYPBG4+KQGfPyGueHbfMhxGfBYjtigphTFTovC8ZH4DHNhOPqoba60U8ZA==,iv:2+plAKQleOcJUbfElKhTrhLAqA9yfXGeHVfeCRSICJo=,tag:0SzJP6lFym630FCmNlh7ww==,type:str]
hydra:
    host: ENC[AES256_GCM,data:OYfNfcMfzvN/Jp5c6jXkh7/b8iUxkEaZ3Q==,iv:JGUwclGMRwEotbx03Q6DN2h0zGUa0i9NH9qY3G9+j80=,tag:+X63hSz8gNuEpZ8/56+L0w==,type:str]
    password: ENC[AES256_GCM,data:yK8q7I9uRTlBxVvWks25ng==,iv:xUmpsUbLNSJ4ZU4YxFi/0AWLpMh+WkEz4volsxaFzmk=,tag:Xr2kFBl/8IS5wSD/H6izKg==,type:str]
aws:
    access_key: ENC[AES256_GCM,data:76zFXRKTSPyfQfrvEdXD4MUu278=,iv:oH3DuG8DIE4uk/ETmFWoAXYoq2qtpNjlVFTAv1tXmig=,tag:a/FwaIFTEVmXd2hukEHlsg==,type:str]
    secret_key: ENC[AES256_GCM,data:mvxvpeHGSWkr06pB1Kk93HzkFRZoBQrdchlm4jsBKxSmnEeElN8+/Q==,iv:bnJZMlCalYuBl5OpX8jIOgUk/n3jDVonfTtTUBBsawM=,tag:CMIqEYATr2eERXnAhqP3Gg==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age143mhvlqr6lxvmkd8pehuxufy0a9xt43wpp38fk80t77jpquzm3aqg7k48u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtODNXbytyRmU4TXdWUU5V
            Q0ZGWmdsdlozWUpLN08zYzRJbHd3TEhnRHgwCk9WNjBjdGhjQldwa3gwbmdOZDBG
            Rjl6clI4SEE1VXhtK0hBaWpKZXNIelEKLS0tIG5UaENDRVFpdkFRanRENUhFYXYw
            dzFYM2VqSE1Nd2tEbXZSSXZoQTdUWEEKY/5ezRRiljh66mcmuJ0f6j7T+djPJaMA
            Px6SbKOhJH0jrg6FswNukMg9qVT4oOdOD6WOTzitssvFcT8iMAkzrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T07:31:55Z"
    mac: ENC[AES256_GCM,data:tchd/Ad5VvrT4uTDnZYkQAUGS32yjoBhZvdDB+1CpzH7a8+19qEN95d4CmekEGrJfjTsHO5f5C2ny5OYwZtb2+FE4HfK3mZEL4wHlHH+RlSLItuPHwoknPrizSoO2HhZJalFeFpxpfnw8N7mP3WS/+UyrKiBxCSyqMv/4d99kcs=,iv:xpy/400qs5ZIqbR+Da/ECMn4w3efaZH7jZu8R8pSmME=,tag:Y+pC5bvWE0gG/qrxGZJi6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
