cloudflare:
    api_token: ENC[AES256_GCM,data:t7dA1mOoWyNeK6eIsa8XXfDWidKipOX5GG3msezaFQGlR1prm7vfPg==,iv:1Dr22sRQp8BT5tu06y46lHHuRFU6+GqAzDd6TIYgQSg=,tag:aRluxDmedLnCuWar/P5Xng==,type:str]
    account_id: ENC[AES256_GCM,data:1CD7kZppfZul3X2kXYwYc6XW34jQG54eK1zpJWc6NW0=,iv:F0L3NSw/1UDb9pXUY18JyeYqv7ohECWLumN9sB/XL8o=,tag:SbpF53zc4pnS3GJM/nqzmQ==,type:str]
    r2_access_key: ENC[AES256_GCM,data:fr7uVRnsaQcHshV19m2MtCjOuWC17+JK2TQFD/RBJVk=,iv:67RV3S0VY6ygOww8pXE/uDgHH+fmLJXz6dg8KOo7GxY=,tag:VGMeP3uwHvS5u5IhpxC/0w==,type:str]
    r2_secret_key: ENC[AES256_GCM,data:EawblxTieaunOLXFInZw5Cy+OaVDcRazcEsbb6zfyu/GvhBydiT7Jtf2O+OWtnA98n2nfidkKQu1ke5+u9lOkw==,iv:HotwSnU7gjRZ8FiWmeMVUr6+ArOOYXPGHMNsd/f0ckY=,tag:7ihKDdwdfQ5Jq7kNK6XBHQ==,type:str]
hcloud:
    hcloud_token: ENC[AES256_GCM,data:IBrnP/LyCcjG3KJgUUAmiFd2kuNBJYPBG4+KQGfPyGueHbfMhxGfBYjtigphTFTovC8ZH4DHNhOPqoba60U8ZA==,iv:2+plAKQleOcJUbfElKhTrhLAqA9yfXGeHVfeCRSICJo=,tag:0SzJP6lFym630FCmNlh7ww==,type:str]
aws:
    access_key: ENC[AES256_GCM,data:76zFXRKTSPyfQfrvEdXD4MUu278=,iv:oH3DuG8DIE4uk/ETmFWoAXYoq2qtpNjlVFTAv1tXmig=,tag:a/FwaIFTEVmXd2hukEHlsg==,type:str]
    secret_key: ENC[AES256_GCM,data:mvxvpeHGSWkr06pB1Kk93HzkFRZoBQrdchlm4jsBKxSmnEeElN8+/Q==,iv:bnJZMlCalYuBl5OpX8jIOgUk/n3jDVonfTtTUBBsawM=,tag:CMIqEYATr2eERXnAhqP3Gg==,type:str]
disk_key: ENC[AES256_GCM,data:IMq+zpV0YLHIHsjlOOeX8A==,iv:G8ECKYxD+TWvM87Wn9wa4TryGi5I5iX530qdHEjG5QM=,tag:uLsyNvLxXi4nyMFoX9zHxA==,type:str]
ssh_keys:
    hcax:
        ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:nAu0zWWkdlF7GR3Zr82lTIT+ECwDe56Cou8ctnFoBt7QEKM9ISk8qrfn8uLHssQ04NmekQJw/AqcBOi2ByXCuIOL/C5j2sgfAM6Q1D5D0YZRbLWxXj1CbsnD,iv:lus52uiHVNHxIc+xO+fsUykRcqyd5DIj7BZVIpWvo7s=,tag:FxUKecMCsmvzJ/q3ENoA8g==,type:str]
        ssh_host_ed25519_key: ENC[AES256_GCM,data:oSnXzAsW9DHI+QWKJZ8fUBUeo79CYRS5pTlzkm5MXJ26X1H2Pz2u7jv5W3B90khNoAlRU5dUGUwla3lzsyEx1tABw9ZMUF5HbXN0bFNibGAVxHfs5D+X/n7gRZscNGGkY2HBGvKJoM16roXPPPS0dMa6l2ODj6MIcOCRtpqhdZkYoYw3zSN25OU1RM6QPeVeGLVJOJNr9d+stKjjwtw6ULigthCOoMN240Mx/BiSvZQeua4hCOtsFdxF/1awB8e1IJAZfaozRZIWTyxXjL0QXUQcr6L1MwyANEmdwUXKotPDEqhd/C3K5VXQQihCNvhmGk29EY9E7qkQlOQOKovR47svy4zxfHw8Q0tNZm9wReBmMcrdYiKQETAsTaYPcbkF3fLuijOrrukDQFQPaFRhHEh2RwzzzZpyLtrG56jNt635KqFp2oqIfFpaGr7sPBcccklMKBEXpsXWnuGGMrVQAEO5OqJj5lB8YTzCl6dCmbUo5DgICTc+qNRswTC8b1dfbxCYwz1UXWrU+us2OGTa,iv:zeiwwq59h+IerQdbBtby7/a7KR2qMVyGAoElXqpXUo0=,tag:4HZVhuzP5Zerh29jNedZQg==,type:str]
    hcax_initrd:
        ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:TjCDjnxXRMmFI/2YVkfKpVW3JncdZwvIhPK41cKGoRBeAqc7O8nryQBIsJg/F0K6resDOUfOUG/1AjM05F1xajYa6wSPRGpCqDRgqjhk3DUGKKPZHJsPJnNg,iv:JajPyACPjYC67+mDGMjNwzOlo+IVU6W94k7OJ++h5Z8=,tag:Xi5jBa2SCJCzIZ8uupGdQQ==,type:str]
        ssh_host_ed25519_key: ENC[AES256_GCM,data:jxz9mf98x2XFmfqV4gioIz3wBXnMzatV0ihi/Y18M2wOytD+GSruiLR+7pZct+VKoXCkSeCwE6/BP2r86lPicvfD+EIPnMZgZ5amsqlAk3h6dZSYF4S7Y79MsxsFcpSY1yPb6HwtCHY+jsMAfRNUyoVZEmY2mpwUaIfJsgFgKgdZ6yZfDZzmdN8x9m+5PFmRiqiBk8iQU5G9EMKuuJOQkhp6wLPuSlSCZwavELmk5D9ltlufCzKw4Ie5LwasOnfGj80o1puFyD9RDwhn4CcsxTwALqHLRWZvaNacSoAXuMxaFjuxLRYQXX1XQcnj1PqtzJBJAPBoag+qDEnYWo7w2T3W/rJhCfr3Aw0c/C6FsfWhRPP98tw17uHFQ0J6meFpCTi7BmZw41zcPIOwkuJHL/NPnqWr3EDZ0lR91wSEUuk8NkYmNpIU7BjOIZLUhOUUHvhCIkIet9M0Wz8qW2wqRsAKqsWyMlCnYj3zA3AeXS4TsYRgZ1waP4t6pmmNDOoo97DueNX9gAS8J6xi+/DO,iv:cfusqCCHDNu29jvJC+Zn7XsRMoEpz6II2wP4cHUo6Ak=,tag:Ke8jhdBE/8cnVsarPu1Jug==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9azc8t9pr8580e035dlcrpu5cqvt4q3fvshmkd4ym54sfpxrdwq2qjtpn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRWpVbXpoUHVEc0RZRkph
            OWVOb1MvUVhkMHFkaXU2OGF6Qjkxck8xK25RCnJ5UTVhNVZOVHQzUUZIYTRqUll0
            aUNvdmNEOUZId1Z2VEo2RFdkbWFBdlUKLS0tIDJDd1p6eTdoMCtRZUxaZ2Y1QVk5
            ZDE5ajR5MW1veEl4akpBR3VtTnVLZFUKLkTjv8+hXooRUYWNqYf9WEZSlVj17knG
            5q+s2VJLP24qo9CNMO9WqmKT1CuGre3OWwD1QYCd5rDMcZ7o4Ica1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age143mhvlqr6lxvmkd8pehuxufy0a9xt43wpp38fk80t77jpquzm3aqg7k48u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRktVajMySktDS3czdmJx
            M0hMdnVSWUoza3Z5WjVTZDBJbEtyZXFzTFZrCjNlSENidFo4ODhNQnZBcmRZdkFl
            dTdQUEkxMHN2L0xJR3VIckN2a0ZzeXcKLS0tIGNtNU83R3drcS95TDJORWIrUG5u
            Um1QcE5EMjhYNC9FQ3dEamY4OGdET0kKyZ4w0m/100DB/u/6jbLrloBdNGxdnReU
            3nxKJ/hfMOJUfSnYWDu7tTBXPyejQ/c5Kiw0Yf7T3KK/CYphg45ePA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vg42qr9mnrfgn3l34p974lacr8gqa79kxlvw2cnkzzxuaqdr69lqu0ueex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS1creStoWVBEUWVPRmg4
            NjAwVmlBS0NXVS96QWVhUGE0Y0l3WTJDYXpnCmNxQnJ2QWZ4RkxMNDNtaW83cVpQ
            bE12aXlJQ2svbHcwMXRGVUdxUWZxbmcKLS0tIGpYcWI4aHEyZ0lwVzZCUExTQ2Fp
            ajA5WS91Vm5RajhzVElNSzhvcWhGYW8KgKcUq/ZaPa7tf1UdTCtmT9v2UZJfDGCo
            ChKDTOiuCKNYSTYK1aYyfgi7+GVdO3eM/Th2wzw9FHYXtkZjLgpSoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1acupz46dkd20nqq8mktc8v7chrws6hnvcw2r5hpyd35ajg2gtdhqfx9uf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcWk0TjFDTllIaHV6bGY4
            ZGRRa3VNYkljNFZoYmZTN09lVEw0TTNSM2dzClJpNXowd09tVXA3NWdpbXJLVE9S
            ajRrTXNHdDIvcmZ4dWY0T2pTd01JeXcKLS0tIGVrVjcydzE3bU9yaHl5S3FlbmJp
            SDVlWmkrWUgybzV5MEJZWGhpS1BTOUUKv+qMoupGDXrvKIA9dD6v92BbOKPx9gUY
            N1JUZbkEVouxicUUz0JqHQZ1/U3+Nhj0G30A/TUoEhKbZ+5g0R8DaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T01:17:43Z"
    mac: ENC[AES256_GCM,data:BYUThdHMa6eSNkGzYFHB31RPZZurQUkYT5hMytsMDZt3eLY271UbxEPEwiBFf14LjPuE1sXMOuT1qkS+lpcRF1exiV0+jGTDSwCnqvD4TjSug0GE3XFIut81il19ahLHUcIo0HQRYfqdSBFvbLKWJYbDHHaboEv9nGkWzDIwUZ8=,iv:TRTrKjVcYz7BjGUQZKD17eycUDv5oPwfRecL53AfcGg=,tag:dWEi4FIRNi76yME2s/Ir/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
