[catppuccin-alacritty]
src.git = "https://github.com/catppuccin/alacritty"
fetch.github = "catppuccin/alacritty"

[catppuccin-bat]
src.git = "https://github.com/catppuccin/bat"
fetch.github = "catppuccin/bat"

[catppuccin-btop]
src.git = "https://github.com/catppuccin/btop"
fetch.github = "catppuccin/btop"

[catppuccin-fcitx5]
src.git = "https://github.com/catppuccin/fcitx5"
fetch.github = "catppuccin/fcitx5"

[catppuccin-fish]
src.git = "https://github.com/catppuccin/fish"
fetch.github = "catppuccin/fish"

[catppuccin-foliate]
src.git = "https://github.com/catppuccin/foliate"
fetch.github = "catppuccin/foliate"

[catppuccin-starship]
src.git = "https://github.com/catppuccin/starship"
fetch.github = "catppuccin/starship"

[catppuccin-palette]
src.git = "https://github.com/catppuccin/palette"
fetch.github = "catppuccin/palette"

[catppuccin-qt5ct]
src.git = "https://github.com/catppuccin/qt5ct"
fetch.github = "catppuccin/qt5ct"

[catppuccin-zsh]
src.git = "https://github.com/catppuccin/zsh-syntax-highlighting"
fetch.github = "catppuccin/zsh-syntax-highlighting"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict"

[naiveproxy]
src.github = "klzgrad/naiveproxy"
fetch.url = "https://github.com/klzgrad/naiveproxy/releases/download/$ver/naiveproxy-$ver-linux-x64.tar.xz"

[ttf-ms-win10]
src.git = "https://github.com/streetsamurai00mi/ttf-ms-win10"
fetch.github = "streetsamurai00mi/ttf-ms-win10"

[ttf-wps-fonts]
src.git = "https://github.com/BannedPatriot/ttf-wps-fonts"
fetch.github = "BannedPatriot/ttf-wps-fonts"

[kanagawa-gtk]
src.git = "https://github.com/Fausto-Korpsvart/Kanagawa-GKT-Theme"
fetch.github = "Fausto-Korpsvart/Kanagawa-GKT-Theme"
