[palette]
src.git = "https://github.com/catppuccin/palette"
fetch.github = "catppuccin/palette"

[fishTheme]
src.git = "https://github.com/catppuccin/fish"
fetch.github = "catppuccin/fish"

[fcitx5-catppuccin]
src.git = "https://github.com/catppuccin/fcitx5"
fetch.github = "catppuccin/fcitx5"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict"

[ttf-ms-win10]
src.git = "https://github.com/streetsamurai00mi/ttf-ms-win10"
fetch.github = "streetsamurai00mi/ttf-ms-win10"

[ttf-wps-fonts]
src.git = "https://github.com/BannedPatriot/ttf-wps-fonts"
fetch.github = "BannedPatriot/ttf-wps-fonts"
