[caddy]
src.github = "caddyserver/caddy"
fetch.github = "caddyserver/caddy"

[catppuccin-alacritty]
src.git = "https://github.com/catppuccin/alacritty"
fetch.github = "catppuccin/alacritty"

[catppuccin-bat]
src.git = "https://github.com/catppuccin/bat"
fetch.github = "catppuccin/bat"

[catppuccin-btop]
src.git = "https://github.com/catppuccin/btop"
fetch.github = "catppuccin/btop"

[catppuccin-fcitx5]
src.git = "https://github.com/catppuccin/fcitx5"
fetch.github = "catppuccin/fcitx5"

[catppuccin-fish]
src.git = "https://github.com/catppuccin/fish"
fetch.github = "catppuccin/fish"

[catppuccin-foliate]
src.git = "https://github.com/catppuccin/foliate"
fetch.github = "catppuccin/foliate"

[catppuccin-starship]
src.git = "https://github.com/catppuccin/starship"
fetch.github = "catppuccin/starship"

[catppuccin-zsh]
src.git = "https://github.com/catppuccin/zsh-syntax-highlighting"
fetch.github = "catppuccin/zsh-syntax-highlighting"

[cloudflare]
src.git = "https://github.com/caddy-dns/cloudflare"
fetch.github = "caddy-dns/cloudflare"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict"

[forwardproxy]
src.git = "https://github.com/klzgrad/forwardproxy"
fetch.github = "klzgrad/forwardproxy"

[naiveproxy]
src.github = "klzgrad/naiveproxy"
fetch.url = "https://github.com/klzgrad/naiveproxy/releases/download/$ver/naiveproxy-$ver-linux-x64.tar.xz"

[ttf-ms-win10]
src.git = "https://github.com/streetsamurai00mi/ttf-ms-win10"
fetch.github = "streetsamurai00mi/ttf-ms-win10"

[ttf-wps-fonts]
src.git = "https://github.com/BannedPatriot/ttf-wps-fonts"
fetch.github = "BannedPatriot/ttf-wps-fonts"
