[fcitx5Theme]
src.git = "https://github.com/catppuccin/fcitx5"
fetch.github = "catppuccin/fcitx5"

[fishTheme]
src.git = "https://github.com/catppuccin/fish"
fetch.github = "catppuccin/fish"

[foliateTheme]
src.git = "https://github.com/catppuccin/foliate"
fetch.github = "catppuccin/foliate"

[qtcreatorTheme]
src.git = "https://github.com/catppuccin/qtcreator"
fetch.github = "catppuccin/qtcreator"

[rioTheme]
src.git = "https://github.com/catppuccin/rio"
fetch.github = "catppuccin/rio"

[palette]
src.git = "https://github.com/catppuccin/palette"
fetch.github = "catppuccin/palette"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict"

[naive]
src.github = "klzgrad/naiveproxy"
fetch.url = "https://github.com/klzgrad/naiveproxy/releases/download/$ver/naiveproxy-$ver-linux-x64.tar.xz"

[ttf-ms-win10]
src.git = "https://github.com/streetsamurai00mi/ttf-ms-win10"
fetch.github = "streetsamurai00mi/ttf-ms-win10"

[ttf-wps-fonts]
src.git = "https://github.com/BannedPatriot/ttf-wps-fonts"
fetch.github = "BannedPatriot/ttf-wps-fonts"
