# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  batTheme = {
    pname = "batTheme";
    version = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
      fetchSubmodules = false;
      sha256 = "sha256-6WVKQErGdaqb++oaXnY3i6/GuH2FhTgK0v4TN4Y0Wbw=";
    };
    date = "2022-11-10";
  };
  btopTheme = {
    pname = "btopTheme";
    version = "89ff712eb62747491a76a7902c475007244ff202";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "89ff712eb62747491a76a7902c475007244ff202";
      fetchSubmodules = false;
      sha256 = "sha256-J3UezOQMDdxpflGax0rGBF/XMiKqdqZXuX4KMVGTxFk=";
    };
    date = "2023-06-07";
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20230823";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20230823.dict";
      sha256 = "sha256-aPJN8NWxTTVol85pAqx2O6JFwtJaOSiBZ8DRWsPzCm8=";
    };
  };
  fcitx5Theme = {
    pname = "fcitx5Theme";
    version = "ce244cfdf43a648d984719fdfd1d60aab09f5c97";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fcitx5";
      rev = "ce244cfdf43a648d984719fdfd1d60aab09f5c97";
      fetchSubmodules = false;
      sha256 = "sha256-uFaCbyrEjv4oiKUzLVFzw+UY54/h7wh2cntqeyYwGps=";
    };
    date = "2022-10-05";
  };
  fishTheme = {
    pname = "fishTheme";
    version = "91e6d6721362be05a5c62e235ed8517d90c567c9";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "91e6d6721362be05a5c62e235ed8517d90c567c9";
      fetchSubmodules = false;
      sha256 = "sha256-l9V7YMfJWhKDL65dNbxaddhaM6GJ0CFZ6z+4R6MJwBA=";
    };
    date = "2023-04-27";
  };
  foliateTheme = {
    pname = "foliateTheme";
    version = "40ae4528569d864cba8f4e64716c3361f7244209";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "foliate";
      rev = "40ae4528569d864cba8f4e64716c3361f7244209";
      fetchSubmodules = false;
      sha256 = "sha256-tpZj1/gV2TEdcequ+0EFz/3Hv4UN2dcdbJvT8a/i+hs=";
    };
    date = "2023-02-01";
  };
  naive = {
    pname = "naive";
    version = "v117.0.5938.44-1";
    src = fetchurl {
      url = "https://github.com/klzgrad/naiveproxy/releases/download/v117.0.5938.44-1/naiveproxy-v117.0.5938.44-1-linux-x64.tar.xz";
      sha256 = "sha256-bIffHXJN7mtYRgBJPKymLdgnQ0naT8ZEyDzTAhP2J74=";
    };
  };
  palette = {
    pname = "palette";
    version = "205dd54c6158b7648621cf9fd00e91f03888ce7e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "palette";
      rev = "205dd54c6158b7648621cf9fd00e91f03888ce7e";
      fetchSubmodules = false;
      sha256 = "sha256-y14fd8lvnG9hNY6CRU0JgxWouexEw91aIEMkr1NaM/4=";
    };
    date = "2023-07-10";
  };
}
