name: Deploy
on: [push, workflow_dispatch]
jobs:
  check:
    uses: ./.github/workflows/check.yml

  deploy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.OPS_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Deploy remote hosts
        run: nix develop --command colmena apply
