name: Deploy
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Deploy remote hosts
        run: nix develop --command colmena apply
      - name: Send notification
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://ntfy.snakepi.xyz
          bearerToken: ${{ secrets.NTFY_TOKEN }}
          data: |
            {
              "topic": "dev",
              "title": "Deploy NixOS",
              "message": "Deploy successfully."
            }
