name: Update
on:
  schedule:
    - cron: 0 21 * * *
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Flake update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          commit-msg: "bump: flake inputs"
          branch: bump_flake_inputs
          pr-title: "bump: flake inputs"
          pr-body: |
            Automated changes by GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: merge-queue

  update-nvfetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Create pr_body.txt
        run: |
          nix run .#nvfetcher -- \
            --build-dir overlays/_sources \
            --config overlays/nvfetcher.toml \
            --changelog pr_body.txt
          GIT_COMMIT_MESSAGE="$(cat body.txt)"
          echo "$GIT_COMMIT_MESSAGE" >> $GITHUB_ENV
          rm -f pr_body.txt
      # - name: Read pr_body.txt
      #   id: pr_body
      #   uses: juliangruber/read-file-action@v1
      #   with:
      #     path: ./pr_body.txt
      # - name: Remove PR body template files
      #   shell: bash
      #   run: rm -f pr_body.txt
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "bump: overlays sources"
          branch: bump_overlays_sources
          delete-branch: true
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          title: "bump: overlays sources"
          labels: merge-queue
          body: |
            Automated changes by GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
