name: Update
on:
  schedule:
    - cron: 0 4 * * *

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

  check:
    steps:
      - name: Nix check
        uses: ./.github/workflows/check.yml

  update:
    steps:
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ github.PAT }}
          pr-title: "ci: update flake.lock"
