name: Update
on:
  schedule:
    - cron: 0 18 * * *
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create github app token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Check flake inputs
        id: check
        run: |
          declare -A inputs=(
            ["nixpkgs"]="github:NixOS/nixpkgs/nixos-unstable"
            ["rx-nvim"]="github:CnTeng/rx-nvim"
            ["ph"]="github:CnTeng/ph"
          )

          check_flake_input() {
            local flake_name=$1
            local flake_url=$2

            local current_rev
            local latest_rev

            current_rev=$(nix flake metadata --json | jq -r ".locks.nodes[\"${flake_name}\"].locked.rev")
            latest_rev=$(nix flake metadata "${flake_url}" --json | jq -r '.revision')

            if [[ "$current_rev" != "$latest_rev" ]]; then
              echo "${flake_name}:"
              echo "  current: $current_rev"
              echo "  latest: $latest_rev"
              return 0
            else
              return 1
            fi
          }

          upgrade=false
          for flake_name in "${!inputs[@]}"; do
            flake_url=${inputs[$flake_name]}
            if check_flake_input "$flake_name" "$flake_url"; then
              upgrade=true
            fi
          done

          echo "upgrade=$upgrade" >>"$GITHUB_OUTPUT"

      - name: Update flake inputs
        uses: DeterminateSystems/update-flake-lock@main
        if: steps.check.outputs.upgrade == 'true'
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-msg: "bump: flake inputs"
          branch: bump_flake_inputs
          pr-title: "bump: flake inputs"
          pr-body: |
            Automated changes by GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: auto-merge

  update-pkgs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create github app token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update packages
        run: |
          nix run nixpkgs#nix-update -- todoist-cli --version=branch --flake --commit

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "bump: packages"
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: bump_packages
          delete-branch: true
          title: "bump: packages"
          body: |
            Automated bump of packages.
          labels: auto-merge
