name: Update
on:
  schedule:
    - cron: 0 18 * * *
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update flake
        uses: DeterminateSystems/update-flake-lock@main
        with:
          commit-msg: "bump: flake inputs"
          branch: bump_flake_inputs
          pr-title: "bump: flake inputs"
          pr-body: |
            Automated changes by GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: merge-queue
