name: Update
on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Git config
        run: |
          git config --global user.email "me@snakepi.xyz"
          git config --global user.name "CnTeng"
      - name: Flake update
        run: nix flake update --commit-lock-file
      - name: Nvfetcher update
        run: nix develop --command nvfetcher -o overlays/_sources -c overlays/nvfetcher.toml
      - name: Flake check
        run: nix flake check --all-systems
      - name: Git push
        run: git push
