name: Update
on:
  schedule:
    - cron: 0 18 * * *
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Use nix cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Compare nixpkgs version
        id: compare
        run: |
          current_fp=$(nix flake metadata nixpkgs --json | jq -r .fingerprint)
          latest_fp=$(nix flake metadata github:NixOS/nixpkgs/nixos-unstable --json | jq -r .fingerprint)

          if [ "$current_fp" = "$latest_fp" ]; then
            echo "should_upgrade=false" >>"$GITHUB_OUTPUT"
          else
            echo "should_upgrade=true" >>"$GITHUB_OUTPUT"
          fi

      - name: Update flake
        uses: DeterminateSystems/update-flake-lock@main
        if: steps.compare.outputs.should_upgrade == 'true'
        with:
          commit-msg: "bump: flake inputs"
          branch: bump_flake_inputs
          pr-title: "bump: flake inputs"
          pr-body: |
            Automated changes by GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: merge-queue
