name: Update
on:
  schedule:
    - cron: 0 21 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - name: Flake update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "bump: flake inputs"
          pr-labels: automated
      - name: Git config
        run: |
          git config --global user.name "CnTeng"
          git config --global user.email "me@snakepi.xyz"
      - name: Nvfetcher update
        run: |
          nix run .#nvfetcher -- -o overlays/_sources -c overlays/nvfetcher.toml

          if [ -n "$(git status --porcelain)" ]; then
            git commit -a -m "bump: overlays sources"
            nix flake check --all-systems
            git push
          fi
