name: Update
on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check.yml

  update:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "ci: update flake.lock"
